### ISSUE TITLE
Periodic Boundary Condition

### ISSUE THREAD

**Issue by omidshy** [atomistic-machine-learning/schnetpack#389]
Hi,
I have a couple of questions regarding the use of periodic boundary conditions (PBC) in SchNetPack.

For training a model on energy and forces using PBC; the *unit cell* and *pbc* info should be present in the dataset, and as environment provider ``ase`` or ``torch`` should be used with a cutoff. Is this correct?

For running MD simulations, is PBC supported in the current master branch via the SchNetPack-MD package?
If so, is it enough to include the ``Lattice`` and ``pbc`` info in the extended XYZ file of the initial structure, and perhaps setting the ``neighbor_list: ase`` in the calculator section of the MD conf file?

Are MD simulations with PBC possible using ASE interface?

Thanks.

**Comment by mgastegger** [comment]
> For training a model on energy and forces using PBC; the 'unit cell' and 'pbc' info should be present in the dataset, and as environment provider 'ase' or 'torch' should be used with a cutoff. Is this correct?

That is correct. Regarding `_cell` and `_pbc` properties, when a new dataset is created from ASE `Atoms`, both properties should be taken from the `Atoms` object automatically.

> For running MD simulations, is PBC supported in the current master branch via the SchNetPack-MD package?
If so, is it enough to include the 'Lattice' and 'pbc' info in the extended XYZ file of the initial structure, and perhaps setting the 'neighbor_list: ase' in the calculator section of the MD conf file?

PBCs are supported in the current master branch. The steps are as you described. `Lattice` and `pbc` need to be included in the extended XYZ input and the neighborlist should be set to ASE. 

It is also possible to add a barostat to the simulations. For this, stress tensor computation needs to be enabled in the calculator with the `stress_handle` and `stress_conversion` keywords in the `calculator` block. In SchNetPack models the default label for stress is `stress`, e.g.
```
calculator:
...
  stress_handle: stress
  stress_conversion: eV/Angstrom/Angstrom/Angstrom
```
For the barostat, two options are available: isotropic `nhc_iso` and anisotropic `nhc_aniso` Nose-Hover barostats with built in thermostats. The entry in the dynamics block could e.g. look like this:
```
  thermostat: null
  barostat:
    type: nhc_iso
    target_pressure: <x / bar>
    temperature: <x / K>
    time_constant: <x/  fs>
    time_constant_cell: <x / fs>
    time_constant_barostat: <x / fs>
```

> Are MD simulations with PBC possible using ASE interface?

They are not possible with the `AseInterface` class, however the `SpkCalculator` can be used with PBCs in ASE routines.
For this, the `environment_provider` should be changed to ASE and the `stress` and `stress_units` arguments need to be set properly.
